name:  Mejora de c贸digo
description: Sugerencia para mejorar partes del c贸digo existente.
title: "[SUGERENCIA]: "
labels: ["mejora", "refactor", "optimizaci贸n"]
assignees:
  - tu_usuario_github

body:
  - type: markdown
    attributes:
      value: |
        隆Gracias por contribuir con una sugerencia para mejorar el c贸digo! Por favor llena los siguientes campos:

  - type: input
    id: archivo
    attributes:
      label:  Archivo o m贸dulo afectado
      description: Especifica en qu茅 archivo o m贸dulo se encuentra la parte del c贸digo a mejorar.
      placeholder: src/componentes/UsuarioController.java
    validations:
      required: true

  - type: textarea
    id: descripcion
    attributes:
      label:  Descripci贸n de la mejora propuesta
      description: Explica claramente cu谩l es la mejora y por qu茅 ser铆a 煤til implementarla.
      placeholder: Mejorar el uso de bucles en la funci贸n renderUsuarios para aumentar la eficiencia...
    validations:
      required: true

  - type: textarea
    id: justificacion
    attributes:
      label:  Justificaci贸n t茅cnica
      description: 驴Cu谩l es el motivo t茅cnico para esta mejora? 驴Se alinea con buenas pr谩cticas, patrones de dise帽o, rendimiento?
      placeholder: El m茅todo actual tiene una complejidad O(n虏), lo cual podr铆a afectar el rendimiento con grandes vol煤menes de datos...
    validations:
      required: true

  - type: textarea
    id: solucion
    attributes:
      label:  Posible soluci贸n o referencia
      description: (Opcional) Si tienes una idea de c贸mo resolverlo o conoces documentaci贸n que lo respalde, comp谩rtela aqu铆.
      placeholder: Podr铆amos implementar un diccionario en lugar de recorrer la lista dos veces...
    validations:
      required: false

  - type: dropdown
    id: prioridad
    attributes:
      label:  Prioridad sugerida
      description: 驴Qu茅 tan urgente o beneficiosa consideras que es esta mejora?
      options:
        - Alta
        - Media
        - Baja
      default: 1